### ISSUE TITLE
Add Tooltip explanation to Self-Employment question

### ISSUE THREAD

**Issue by alexsoble** [mRelief/documents_api#243]
cc @RoseAfriyie

**Comment by genevievenielsen** [comment]
Here is the copy for the tooltip on the employment question - 

"Self-employment includes small business, sales of cosmetics and furniture, farming, dressmaking, child care, home repair, yard work, animal care, roomers or boarders. If you received rental income due to managing a property, include this if it is at least an average of 20 hours per week."

**Comment by alexsoble** [comment]
Fixed via #244.

**Comment by genevievenielsen** [comment]
Remove dressmaking from the list. 
Remove sales of furniture.
